language: csharp
solution: Project.sln
dotnet: 2.1.401
script:
  - dotnet build Api/
branches:
  only:
  - master
  - stable
  - homol
 notifications:
    slack: travisaspnetcore21:9G5NGiQxRduCX875uTL3POAT
      on_success: always