language: csharp
solution: Project.sln
dotnet: 2.1.401
script:
- dotnet build Api/
branches:
  only:
  - master
  - stable
  - homol
notifications:
  slack:
      rooms:
      - travisaspnetcore21:9G5NGiQxRduCX875uTL3POAT#notifications
    # secure: WLX99CfCov8udczLD9dPv2ZrNIPtqmjOjr6K3AQHHdp01QSnfqpFW+QdLT+ka3P3gtS4iZldkB64IAh+WeA9HgSFLe55EfMh+whpn6uhVKm5ZGNiGvMb7gmkUamVcYa1uVm/Jrl2VveKx+3AZQAyzJizgIjwTFUR5TT3z3dgFIJFFcB8+SsIaatw+Lxr2wviTPr6fXOZ7OwNC8CTFXdqyMgWJPl1/er7tMl2b2CFXgRezBwjDptu9XH2LW7L8EiMegbh9EDQB3Wk8OFR81sdFn6Vs8IQ+T9bPWjJj37ropGLWhzfNcEPQjhBr10hmVSP9C12hVmy0X9fygh7B5eIWZcT0o4XnwHsa+Ll95p8iAekr3cx5LsRY+lNxXrHPMb/URkr4Mhm5blxyreGp3gSYaFyITH3RrmqRogC7OHidEPxesfs+B2ntwILgH6CseNPQ/CdJpRgtfaSnJnPzIcXdm72Dqn+vA4HDu+G8NNMvbXNxJsOkzOTvMajgdfxuPVMyUrwQTDbh1U69cfNaY39EEMyuyswphznwLwlKEKqulAsvqkymaHaL+gdlM9ClOR49es56GCbRPkPZ9b7GpFjV2df36IieWNZKtWFr0L/VWBUl+zDP+52E3TJNrwOkbtE8f5T4qznD669r0eAM8ljcDzw0oBV3fmwyUJtayMKJ9k=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"